language: cpp
sudo: required
dist: xenial

branches:
  only:
    - master
    - travis

matrix:
  include:
  - compiler: clang
    addons:
      apt:
        packages:
        - libboost-all-dev
        - libgfortran3
        - gfortran
        - openmpi-bin
        - openmpi-common
        - openmpi-doc
        - libopenmpi-dev
        - libblas-dev
        - liblapack-dev
        - libfftw3-dev
        - libgmp-dev
        - hdf5-tools
        - libhdf5-serial-dev
        - python-h5py
        - python-dev
        - python-numpy
        - python-scipy
        - python-jinja2
        - python-matplotlib
        - ipython
        - python-mpi4py
        - python-mako
        - clang-format-5.0
        - libclang-5.0-dev
        - python-clang-5.0
        - libnfft3-dev
  - compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test' # GCC 7
        packages:
        - g++-7
        - libboost-all-dev
        - libgfortran3
        - gfortran
        - openmpi-bin
        - openmpi-common
        - openmpi-doc
        - libopenmpi-dev
        - libblas-dev
        - liblapack-dev
        - libfftw3-dev
        - libgmp-dev
        - hdf5-tools
        - libhdf5-serial-dev
        - python-h5py
        - python-dev
        - python-numpy
        - python-scipy
        - python-jinja2
        - python-matplotlib
        - ipython
        - python-mpi4py
        - python-mako
        - clang-format-5.0
        - libclang-5.0-dev
        - python-clang-5.0
        - libnfft3-dev
    before_install:
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

before_script:
  # Stop on first error
  - set -e

  # Force CLang to use libc++
  - |
    if [[ "${CXX}" == "clang++" ]]; then                                        \
      CMAKE_CXX_FLAGS="-stdlib=libc++ -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR"; \
      export LD_LIBRARY_PATH=/usr/local/clang-7.0.0/lib:$LD_LIBRARY_PATH;       \
    fi

  # Create directory for installed prerequisites
  - export PREREQS_DIR=$(readlink -f $TRAVIS_BUILD_DIR/../installed)
  - mkdir $PREREQS_DIR

  - cd $TRAVIS_BUILD_DIR/..

  # Download and install Eigen3
  - wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2
  - tar xf 3.3.7.tar.bz2
  - mkdir eigen.build
  - pushd eigen.build
  - cmake $(readlink -f ../eigen-eigen-*) -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR
  - make install
  - popd

  # Build and install TRIQS
  - git clone https://github.com/TRIQS/triqs.git triqs.git
  - pushd triqs.git && git checkout 2.2.2 && popd
  - mkdir triqs.build && pushd triqs.build
  - |
    cmake ../triqs.git                      \
    -DCMAKE_BUILD_TYPE=Debug                \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR     \
    -DCMAKE_CXX_COMPILER=${CXX}             \
    -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"  \
    -DBuild_Documentation=OFF               \
    -DBuild_Tests=OFF
  - make -j3 install
  - source $PREREQS_DIR/share/triqsvars.sh

  # Build and install Pomerol
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/aeantipov/pomerol.git pomerol.git
  - pushd pomerol.git && git checkout master && popd
  - mkdir pomerol.build && pushd pomerol.build
  - |
    cmake ../pomerol.git                    \
    -DCMAKE_BUILD_TYPE=Debug                \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR     \
    -DCMAKE_CXX_COMPILER=${CXX}             \
    -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"  \
    -DTesting=OFF
  - make -j3 install

script:
  # Build, test and install pomerol2triqs
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir pomerol2triqs_installed
  - mkdir pomerol2triqs.build && pushd pomerol2triqs.build
  - |
    cmake ../pomerol2triqs                                              \
    -DCMAKE_BUILD_TYPE=Debug                                            \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../pomerol2triqs_installed \
    -DCMAKE_CXX_COMPILER=${CXX}                                         \
    -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"                              \
    -DPOMEROL_PATH=$PREREQS_DIR
  - make -j3
  - make test
  - make install
