name: CI

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    strategy:
      matrix:
        include:
          - {os: ubuntu-18.04, cc: gcc-7, cxx: g++-7}
          - {os: ubuntu-18.04, cc: clang-8, cxx: clang++-8}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Update apt-get cache
      run: sudo apt-get update

    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get install
        g++-7
        clang-8
        libgfortran3
        gfortran
        libboost-all-dev
        libeigen3-dev
        openmpi-bin
        openmpi-common
        openmpi-doc
        libopenmpi-dev
        libblas-dev
        liblapack-dev
        libfftw3-dev
        libgmp-dev
        hdf5-tools
        libhdf5-dev
        python3-dev
        python3-numpy
        python3-scipy
        python3-matplotlib
        ipython3
        python3-mpi4py
        python3-mako
        libnfft3-dev

    - name: Build & install Pomerol
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        git clone https://github.com/aeantipov/pomerol
        mkdir pomerol/build && pushd pomerol/build
        cmake ..                                 \
          -DCMAKE_BUILD_TYPE=Debug               \
          -DCMAKE_INSTALL_PREFIX=$HOME/install   \
          -DTesting=OFF
        make -j2 install VERBOSE=1
        popd

    - name: Build & install TRIQS
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        git clone https://github.com/TRIQS/triqs --branch 3.0.x
        mkdir triqs/build && pushd triqs/build
        cmake ..                                 \
          -DCMAKE_BUILD_TYPE=Debug               \
          -DCMAKE_INSTALL_PREFIX=$HOME/install   \
          -DBuild_Tests=OFF
        make -j2 install VERBOSE=1
        popd

    - name: Build pomerol2triqs
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        source $HOME/install/share/triqsvars.sh
        mkdir build && pushd build
        cmake ..                                 \
          -DCMAKE_BUILD_TYPE=Debug               \
          -DCMAKE_INSTALL_PREFIX=$HOME/install
        make -j2 install VERBOSE=1
        popd

    - name: Test pomerol2triqs
      run: |
        source $HOME/install/share/triqsvars.sh
        cd build
        ctest --output-on-failure
