name: CI

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, cc: gcc-10, cxx: g++-10}
          - {os: ubuntu-20.04, cc: clang-13, cxx: clang++-13}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Update apt-get cache
      run: sudo apt-get update

    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get install lsb-release wget software-properties-common &&
        wget -O /tmp/llvm.sh https://apt.llvm.org/llvm.sh &&
        sudo chmod +x /tmp/llvm.sh && sudo /tmp/llvm.sh 13 &&
        sudo apt-get install
        g++-10
        clang-13
        libgfortran4
        gfortran
        libeigen3-dev
        openmpi-bin
        openmpi-common
        openmpi-doc
        libopenmpi-dev
        libblas-dev
        liblapack-dev
        libfftw3-dev
        libgmp-dev
        hdf5-tools
        libhdf5-dev
        python3-dev
        python3-numpy
        python3-scipy
        python3-matplotlib
        ipython3
        python3-mpi4py
        python3-mako
        libnfft3-dev

    - name: Download Boost (a C++20 compatible version)
      run: |
           wget -q https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.bz2
           tar -xf boost_1_78_0.tar.bz2
           mv boost_1_78_0 boost

    - name: Install libcommute
      env:
        CXX: ${{ matrix.compiler.cxx }}
      run: |
           git clone https://github.com/krivenko/libcommute libcommute
           mkdir libcommute/build && pushd libcommute/build
           cmake ..                                 \
              -DCMAKE_INSTALL_PREFIX=$HOME/install  \
              -DTESTS=OFF                           \
              -DEXAMPLES=OFF
           make install
           popd

    - name: Build & install Pomerol
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        git clone https://github.com/pomerol-ed/pomerol
        mkdir pomerol/build && pushd pomerol/build
        cmake ..                                         \
          -DCMAKE_BUILD_TYPE=Debug                       \
          -DCMAKE_INSTALL_PREFIX=$HOME/install           \
          -DBoost_INCLUDE_DIR=$(readlink -f ../../boost) \
          -Dlibcommute_DIR=$HOME/install/lib/cmake       \
          -DTesting=OFF                                  \
          -DDocumentation=OFF
        make -j2 install VERBOSE=1
        popd

    - name: Build & install TRIQS
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        git clone https://github.com/TRIQS/triqs --branch 3.1.x
        mkdir triqs/build && pushd triqs/build
        cmake ..                                         \
          -DCMAKE_BUILD_TYPE=Debug                       \
          -DCMAKE_INSTALL_PREFIX=$HOME/install           \
          -DBoost_INCLUDE_DIR=$(readlink -f ../../boost) \
          -DBuild_Tests=OFF
        make -j2 install VERBOSE=1
        popd

    - name: Build pomerol2triqs
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        source $HOME/install/share/triqs/triqsvars.sh
        mkdir build && pushd build
        cmake ..                                 \
          -DCMAKE_BUILD_TYPE=Debug               \
          -DCMAKE_INSTALL_PREFIX=$HOME/install
        make -j2 install VERBOSE=1
        popd

    - name: Test pomerol2triqs
      run: |
        sudo sh -c 'echo -e "\nrmaps_base_oversubscribe = 1" >> /etc/openmpi/openmpi-mca-params.conf'
        source $HOME/install/share/triqs/triqsvars.sh
        cd build
        ctest --output-on-failure
